/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        String PATH = "/Users/pousapan/codefellows-401/java-fundamentals!/linter/src/main/resources/gates.js";
        System.out.println(readFile(PATH));

    }

    public static String readFile(String path) {
        int errorCount = 0;
        String errorMessage = " ";
        try {
            File file = new File(path);
            int lineCount = 1;

            Scanner sc = new Scanner(file);
            while(sc.hasNextLine()) {
                String line =sc.nextLine();
                if ((line.endsWith("{")) || (line.endsWith("}"))){
                }
                else if ((line.contains("if"))||(line.contains("else")) ){
                }
                else if (line.isEmpty()){
                }
                else {
                    if (!line.endsWith(";")) {

                        errorCount++;
                        errorMessage = "Line " + lineCount + ": Missing semicolon.";
                        return errorMessage;
                    }
                }
                lineCount++;
            }
            return errorMessage;
        }

        catch (FileNotFoundException e) {
            System.out.println(e);

        }
        return errorMessage;
    }
    }

